---
spring:
  application:
    name: vasprofile
---
spring:
  profiles: 
    active: default
server:
  port: ${PORT:${SERVER_PORT:0}}
vas-profile: Vas profile for default
---
spring: 
  profiles: north
vas-profile: Vas profile for North
---
spring: 
  profiles: south
vas-profile: Vas profile for South
---
---
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
