---
spring: 
  profiles: north
  application:
    name: vasprofile
vas-profile: Vas profile for North
---
spring: 
  profiles: south
  application:
    name: vasprofile
vas-profile: Vas profile for South
