---
server:
  port: ${PORT:${SERVER_PORT:0}}
---
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
---
vas-profile: default vas profile
---
spring: 
  profiles: north
vas-profile: Vas profile for North
---
spring: 
  profiles: south
vas-profile: Vas profile for South

