---
spring:
  profiles:
    active: default
  application:
    name: vasprofile
server:
  port: ${PORT:${SERVER_PORT:0}} 
vas-profile: Vas profile for default
---
spring: 
  profiles: north
  application:
    name: vasprofile
vas-profile: Vas profile for North
---
spring: 
  profiles: south
  application:
    name: vasprofile
vas-profile: Vas profile for South
