---
spring:
  profiles:
    active: default
  application:
    name: vasprofile
server:
  port: ${PORT:${SERVER_PORT:0}} 
vas-profile: Vas profile for default
---
spring: 
  profiles: north
vas-profile: Vas profile for North
---
spring: 
  profiles: south
vas-profile: Vas profile for South
---
eureka:
  client:
    serviceUrl:
defaultZone: http://localhost:8002/eureka
