---
eureka:
  client:
    serviceUrl:
defaultZone: http://localhost:8002/eureka/
---
vas-profile: default vas profile
---
spring: 
  profiles: north
vas-profile: Vas profile for North
---
spring: 
  profiles: south
vas-profile: Vas profile for South

